# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mealPlanner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
"""
#todo create meal plan tab: 
#todo   load list of meals with assigned to day and meal type
#todo   return list of meals based on number of days / meals selected

#todo   add print meal list function
#todo   create grocery list function to print out required items

#todo view meal list tab:
#todo   

#todo edit meal list tab:
#todo   add function for deleting
#todo   add list for meal type for cmb_list
#todo   add entered feilds of new meal to meal list

"""
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_win_MealPlanner(object):

        def loadEditTable(self,table):
                horzheaders = ["Meal Type","Entrée","Components","Side 1","Side 2","Seasoning & Condiments","Grocery List"]
                connection = sqlite3.connect('mydatabase.db')
                query = "SELECT * FROM tbl_menulist"
                result = connection.execute(query)
                self.tbl_Edit.setColumnCount(7)
                self.tbl_Edit.setRowCount(0)
                for row_number, row_data in enumerate(result):
                        self.tbl_Edit.insertRow(row_number)
                        for column_number, data in enumerate(row_data):
                                self.tbl_Edit.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
                                self.tbl_Edit.setHorizontalHeaderLabels( horzheaders )
                self.tbl_Edit.resizeColumnToContents(7)
                connection.close()

        def loadVeiwTable(self,table):
                horzheaders = ["Meal Type","Entrée","Components","Side 1","Side 2","Seasoning & Condiments","Grocery List"]
                connection = sqlite3.connect('mydatabase.db')
                query = "SELECT * FROM tbl_menulist"
                result = connection.execute(query)
                self.tbl_View.setColumnCount(7)
                self.tbl_View.setRowCount(0)
                for row_number, row_data in enumerate(result):
                        self.tbl_View.insertRow(row_number)
                        for column_number, data in enumerate(row_data):
                                self.tbl_View.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
                                self.tbl_View.setHorizontalHeaderLabels( horzheaders )
                self.tbl_View.resizeColumnToContents(7)
                connection.close()

        def createMealPlan(self, tbale):
                horzheaders = ["Meal Type","Entrée","Components","Side 1","Side 2","Seasoning & Condiments","Grocery List"]
                connection = sqlite3.connect('mydatabase.db')
                crsr = connection.cursor()
                crsr.execute("SELECT * FROM tbl_menulist WHERE mealType='Dinner'")
                self.tbl_CreateMealPlan.setColumnCount(7)
                self.tbl_CreateMealPlan.setRowCount(0)
                for row_number, row_data in enumerate(crsr):
                        self.tbl_CreateMealPlan.insertRow(row_number)
                        for column_number, data in enumerate(row_data):
                                self.tbl_CreateMealPlan.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
                                self.tbl_CreateMealPlan.setHorizontalHeaderLabels( horzheaders )
                self.tbl_View.resizeColumnToContents(7)
                connection.close()


        def selectAll(self):
                self.chkbx_Fri_Br.setChecked(True)
                self.chkbx_Fri_Lu.setChecked(True)
                self.chkbx_Fri_Di.setChecked(True)
                self.chkbx_Wed_Br.setChecked(True)
                self.chkbx_Wed_Lu.setChecked(True)
                self.chkbx_Wed_Di.setChecked(True)
                self.chkbx_Thu_Br.setChecked(True)
                self.chkbx_Thu_Lu.setChecked(True)
                self.chkbx_Thu_Di.setChecked(True)
                self.chkbx_Tue_Br.setChecked(True)
                self.chkbx_Tue_Lu.setChecked(True)
                self.chkbx_Tue_Di.setChecked(True)
                self.chkbx_Mon_Br.setChecked(True)
                self.chkbx_Mon_Lu.setChecked(True)
                self.chkbx_Mon_Di.setChecked(True)
                self.chkbx_Sun_Br.setChecked(True)
                self.chkbx_Sun_Lu.setChecked(True)
                self.chkbx_Sun_Di.setChecked(True)
                self.chkbx_Sat_Br.setChecked(True)
                self.chkbx_Sat_Lu.setChecked(True)
                self.chkbx_Sat_Di.setChecked(True)

        def selectNone(self):
                self.chkbx_Fri_Br.setChecked(False)
                self.chkbx_Fri_Lu.setChecked(False)
                self.chkbx_Fri_Di.setChecked(False)
                self.chkbx_Wed_Br.setChecked(False)
                self.chkbx_Wed_Lu.setChecked(False)
                self.chkbx_Wed_Di.setChecked(False)
                self.chkbx_Thu_Br.setChecked(False)
                self.chkbx_Thu_Lu.setChecked(False)
                self.chkbx_Thu_Di.setChecked(False)
                self.chkbx_Tue_Br.setChecked(False)
                self.chkbx_Tue_Lu.setChecked(False)
                self.chkbx_Tue_Di.setChecked(False)
                self.chkbx_Mon_Br.setChecked(False)
                self.chkbx_Mon_Lu.setChecked(False)
                self.chkbx_Mon_Di.setChecked(False)
                self.chkbx_Sun_Br.setChecked(False)
                self.chkbx_Sun_Lu.setChecked(False)
                self.chkbx_Sun_Di.setChecked(False)
                self.chkbx_Sat_Br.setChecked(False)
                self.chkbx_Sat_Lu.setChecked(False)
                self.chkbx_Sat_Di.setChecked(False)

        def add_checkbox(self):
                for i in range(0, 5):
                        for j in range(1):
                                self.check_boxes = QtWidgets.QCheckBox("checkbox_%i" % i)
                                self.grpBx_Breakfast.addWidget(self.check_boxes,i,j)
                                self.check_boxes.stateChanged.connect(self.count_checkbox)

        def count_checkbox(self):
                nb_ischecked = 0
                for i in range(0, self.grpBx_Breakfast.count()):
                        self.current_checkbox = getattr(self, "checkbox_%i" % i)
                        if self.current_checkbox.isChecked(): nb_ischecked = nb_ischecked + 1
                print(nb_ischecked)



        def setupUi(self, win_MealPlanner):

                font = QtGui.QFont("Calibri",13)

                win_MealPlanner.setObjectName("win_MealPlanner")
                win_MealPlanner.setEnabled(True)
                win_MealPlanner.resize(848, 804)
                win_MealPlanner.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
                win_MealPlanner.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
                self.centralwidget = QtWidgets.QWidget(win_MealPlanner)
                self.centralwidget.setObjectName("centralwidget")
                self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
                self.tabWidget.setGeometry(QtCore.QRect(10, 20, 831, 761))
                self.tabWidget.setTabsClosable(False)
                self.tabWidget.setTabBarAutoHide(False)
                self.tabWidget.setObjectName("tabWidget")
                self.tab_MealPlan = QtWidgets.QWidget()
                self.tab_MealPlan.setObjectName("tab_MealPlan")
                self.frm_Planner = QtWidgets.QFrame(self.tab_MealPlan)
                self.frm_Planner.setGeometry(QtCore.QRect(9, 10, 411, 351))
                self.frm_Planner.setStyleSheet("background-color: rgb(161, 144, 255);")
                self.frm_Planner.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frm_Planner.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frm_Planner.setObjectName("frm_Planner")
                #self.grpBx_Breakfast = QtWidgets.QGroupBox(self.frm_Planner)
                self.grpBx_Breakfast = QtWidgets.QGridLayout(self.frm_Planner)
                self.grpBx_Breakfast.setGeometry(QtCore.QRect(150, 10, 111, 291))
                #self.grpBx_Breakfast.setToolTipDuration(-3)
                #self.grpBx_Breakfast.setStyleSheet("*{\n"
        # "color: blue; \n"
        # "font-size: 18px;\n"
        # "}")
                self.grpBx_Breakfast.setAlignment(QtCore.Qt.AlignCenter)
                #self.grpBx_Breakfast.setFlat(False)
                #self.grpBx_Breakfast.setCheckable(False)
                #self.grpBx_Breakfast.setChecked(False)
                self.grpBx_Breakfast.setObjectName("grpBx_Breakfast")
                # self.splitter = QtWidgets.QSplitter(self.grpBx_Breakfast)
                # self.splitter.setGeometry(QtCore.QRect(50, 20, 16, 261))
                # self.splitter.setOrientation(QtCore.Qt.Vertical)
                # self.splitter.setObjectName("splitter")
                self.chkbx_Mon_Br = QtWidgets.QCheckBox()
                self.chkbx_Mon_Br.setFont(font)
                self.chkbx_Mon_Br.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Mon_Br.setStyleSheet("")
                self.chkbx_Mon_Br.setText("")
                self.chkbx_Mon_Br.setObjectName("chkbx_Mon_Br")
                self.chkbx_Tue_Br = QtWidgets.QCheckBox(self.splitter)
                self.chkbx_Tue_Br.setFont(font)
                self.chkbx_Tue_Br.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Tue_Br.setText("")
                self.chkbx_Tue_Br.setObjectName("chkbx_Tue_Br")
                self.chkbx_Wed_Br = QtWidgets.QCheckBox(self.splitter)
                self.chkbx_Wed_Br.setFont(font)
                self.chkbx_Wed_Br.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Wed_Br.setText("")
                self.chkbx_Wed_Br.setObjectName("chkbx_Wed_Br")
                self.chkbx_Thu_Br = QtWidgets.QCheckBox(self.splitter)
                self.chkbx_Thu_Br.setFont(font)
                self.chkbx_Thu_Br.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Thu_Br.setText("")
                self.chkbx_Thu_Br.setObjectName("chkbx_Thu_Br")
                self.chkbx_Fri_Br = QtWidgets.QCheckBox(self.splitter)
                self.chkbx_Fri_Br.setFont(font)
                self.chkbx_Fri_Br.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Fri_Br.setText("")
                self.chkbx_Fri_Br.setObjectName("chkbx_Fri_Br")
                self.chkbx_Sat_Br = QtWidgets.QCheckBox(self.splitter)
                self.chkbx_Sat_Br.setFont(font)
                self.chkbx_Sat_Br.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Sat_Br.setText("")
                self.chkbx_Sat_Br.setObjectName("chkbx_Sat_Br")
                self.chkbx_Sun_Br = QtWidgets.QCheckBox(self.splitter)
                self.chkbx_Sun_Br.setFont(font)
                self.chkbx_Sun_Br.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Sun_Br.setText("")
                self.chkbx_Sun_Br.setObjectName("chkbx_Sun_Br")
                self.grpBx_Lunch = QtWidgets.QGroupBox(self.frm_Planner)
                self.grpBx_Lunch.setGeometry(QtCore.QRect(260, 10, 61, 291))
                self.grpBx_Lunch.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.grpBx_Lunch.setStyleSheet("*{\n"
        "color: blue; \n"
        "font-size: 18px;\n"
        "}")
                self.grpBx_Lunch.setAlignment(QtCore.Qt.AlignCenter)
                self.grpBx_Lunch.setFlat(False)
                self.grpBx_Lunch.setCheckable(False)
                self.grpBx_Lunch.setObjectName("grpBx_Lunch")
                self.splitter_2 = QtWidgets.QSplitter(self.grpBx_Lunch)
                self.splitter_2.setGeometry(QtCore.QRect(20, 20, 16, 261))
                self.splitter_2.setOrientation(QtCore.Qt.Vertical)
                self.splitter_2.setObjectName("splitter_2")
                self.chkbx_Mon_Lu = QtWidgets.QCheckBox(self.splitter_2)
                self.chkbx_Mon_Lu.setFont(font)
                self.chkbx_Mon_Lu.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Mon_Lu.setText("")
                self.chkbx_Mon_Lu.setObjectName("chkbx_Mon_Lu")
                self.chkbx_Tue_Lu = QtWidgets.QCheckBox(self.splitter_2)
                self.chkbx_Tue_Lu.setFont(font)
                self.chkbx_Tue_Lu.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Tue_Lu.setText("")
                self.chkbx_Tue_Lu.setObjectName("chkbx_Tue_Lu")
                self.chkbx_Wed_Lu = QtWidgets.QCheckBox(self.splitter_2)
                self.chkbx_Wed_Lu.setFont(font)
                self.chkbx_Wed_Lu.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Wed_Lu.setText("")
                self.chkbx_Wed_Lu.setObjectName("chkbx_Wed_Lu")
                self.chkbx_Thu_Lu = QtWidgets.QCheckBox(self.splitter_2)
                self.chkbx_Thu_Lu.setFont(font)
                self.chkbx_Thu_Lu.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Thu_Lu.setText("")
                self.chkbx_Thu_Lu.setObjectName("chkbx_Thu_Lu")
                self.chkbx_Fri_Lu = QtWidgets.QCheckBox(self.splitter_2)
                self.chkbx_Fri_Lu.setFont(font)
                self.chkbx_Fri_Lu.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Fri_Lu.setText("")
                self.chkbx_Fri_Lu.setObjectName("chkbx_Fri_Lu")
                self.chkbx_Sat_Lu = QtWidgets.QCheckBox(self.splitter_2)
                self.chkbx_Sat_Lu.setFont(font)
                self.chkbx_Sat_Lu.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Sat_Lu.setText("")
                self.chkbx_Sat_Lu.setObjectName("chkbx_Sat_Lu")
                self.chkbx_Sun_Lu = QtWidgets.QCheckBox(self.splitter_2)
                self.chkbx_Sun_Lu.setFont(font)
                self.chkbx_Sun_Lu.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Sun_Lu.setText("")
                self.chkbx_Sun_Lu.setObjectName("chkbx_Sun_Lu")
                self.grpBx_Dinner = QtWidgets.QGroupBox(self.frm_Planner)
                self.grpBx_Dinner.setGeometry(QtCore.QRect(320, 10, 71, 291))
                self.grpBx_Dinner.setStyleSheet("*{\n"
        "color: blue; \n"
        "font-size: 18px;\n"
        "}")
                self.grpBx_Dinner.setAlignment(QtCore.Qt.AlignCenter)
                self.grpBx_Dinner.setFlat(False)
                self.grpBx_Dinner.setCheckable(False)
                self.grpBx_Dinner.setChecked(False)
                self.grpBx_Dinner.setObjectName("grpBx_Dinner")
                self.splitter_3 = QtWidgets.QSplitter(self.grpBx_Dinner)
                self.splitter_3.setGeometry(QtCore.QRect(27, 20, 16, 261))
                self.splitter_3.setOrientation(QtCore.Qt.Vertical)
                self.splitter_3.setObjectName("splitter_3")
                self.chkbx_Mon_Di = QtWidgets.QCheckBox(self.splitter_3)
                self.chkbx_Mon_Di.setEnabled(True)
                self.chkbx_Mon_Di.setFont(font)
                self.chkbx_Mon_Di.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Mon_Di.setText("")
                self.chkbx_Mon_Di.setTristate(False)
                self.chkbx_Mon_Di.setObjectName("chkbx_Mon_Di")
                self.chkbx_Tue_Di = QtWidgets.QCheckBox(self.splitter_3)
                self.chkbx_Tue_Di.setFont(font)
                self.chkbx_Tue_Di.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Tue_Di.setText("")
                self.chkbx_Tue_Di.setObjectName("chkbx_Tue_Di")
                self.chkbx_Wed_Di = QtWidgets.QCheckBox(self.splitter_3)
                self.chkbx_Wed_Di.setFont(font)
                self.chkbx_Wed_Di.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Wed_Di.setText("")
                self.chkbx_Wed_Di.setObjectName("chkbx_Wed_Di")
                self.chkbx_Thu_Di = QtWidgets.QCheckBox(self.splitter_3)
                self.chkbx_Thu_Di.setFont(font)
                self.chkbx_Thu_Di.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Thu_Di.setText("")
                self.chkbx_Thu_Di.setObjectName("chkbx_Thu_Di")
                self.chkbx_Fri_Di = QtWidgets.QCheckBox(self.splitter_3)
                self.chkbx_Fri_Di.setFont(font)
                self.chkbx_Fri_Di.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Fri_Di.setText("")
                self.chkbx_Fri_Di.setObjectName("chkbx_Fri_Di")
                self.chkbx_Sat_Di = QtWidgets.QCheckBox(self.splitter_3)
                self.chkbx_Sat_Di.setFont(font)
                self.chkbx_Sat_Di.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Sat_Di.setText("")
                self.chkbx_Sat_Di.setObjectName("chkbx_Sat_Di")
                self.chkbx_Sun_Di = QtWidgets.QCheckBox(self.splitter_3)
                self.chkbx_Sun_Di.setFont(font)
                self.chkbx_Sun_Di.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.chkbx_Sun_Di.setText("")
                self.chkbx_Sun_Di.setObjectName("chkbx_Sun_Di")
                self.grpBx_DaysOfWeek = QtWidgets.QGroupBox(self.frm_Planner)
                self.grpBx_DaysOfWeek.setEnabled(True)
                self.grpBx_DaysOfWeek.setGeometry(QtCore.QRect(20, 20, 131, 281))
                self.grpBx_DaysOfWeek.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.grpBx_DaysOfWeek.setStyleSheet("")
                self.grpBx_DaysOfWeek.setTitle("")
                self.grpBx_DaysOfWeek.setAlignment(QtCore.Qt.AlignCenter)
                self.grpBx_DaysOfWeek.setFlat(False)
                self.grpBx_DaysOfWeek.setObjectName("grpBx_DaysOfWeek")
                self.lbl_Tue = QtWidgets.QLabel(self.grpBx_DaysOfWeek)
                self.lbl_Tue.setGeometry(QtCore.QRect(10, 49, 111, 31))
                self.lbl_Tue.setFont(font)
                self.lbl_Tue.setStyleSheet("color: Blue")
                self.lbl_Tue.setObjectName("lbl_Tue")
                self.lbl_Wed = QtWidgets.QLabel(self.grpBx_DaysOfWeek)
                self.lbl_Wed.setGeometry(QtCore.QRect(10, 88, 111, 31))
                self.lbl_Wed.setFont(font)
                self.lbl_Wed.setStyleSheet("color: Blue")
                self.lbl_Wed.setObjectName("lbl_Wed")
                self.lbl_Mon = QtWidgets.QLabel(self.grpBx_DaysOfWeek)
                self.lbl_Mon.setGeometry(QtCore.QRect(10, 10, 111, 31))
                self.lbl_Mon.setFont(font)
                self.lbl_Mon.setStyleSheet("color: Blue")
                self.lbl_Mon.setObjectName("lbl_Mon")
                self.lbl_Thu = QtWidgets.QLabel(self.grpBx_DaysOfWeek)
                self.lbl_Thu.setGeometry(QtCore.QRect(10, 126, 111, 31))
                self.lbl_Thu.setFont(font)
                self.lbl_Thu.setStyleSheet("color: Blue")
                self.lbl_Thu.setObjectName("lbl_Thu")
                self.lbl_Fri = QtWidgets.QLabel(self.grpBx_DaysOfWeek)
                self.lbl_Fri.setGeometry(QtCore.QRect(10, 161, 111, 31))
                self.lbl_Fri.setFont(font)
                self.lbl_Fri.setStyleSheet("color: Blue")
                self.lbl_Fri.setObjectName("lbl_Fri")
                self.lbl_Sat = QtWidgets.QLabel(self.grpBx_DaysOfWeek)
                self.lbl_Sat.setGeometry(QtCore.QRect(10, 200, 111, 31))
                self.lbl_Sat.setFont(font)
                self.lbl_Sat.setStyleSheet("color: Blue")
                self.lbl_Sat.setObjectName("lbl_Sat")
                self.lbl_Sun = QtWidgets.QLabel(self.grpBx_DaysOfWeek)
                self.lbl_Sun.setGeometry(QtCore.QRect(10, 240, 111, 31))
                self.lbl_Sun.setFont(font)
                self.lbl_Sun.setStyleSheet("color: Blue")
                self.lbl_Sun.setObjectName("lbl_Sun")
                self.btn_SelectAll = QtWidgets.QPushButton(self.frm_Planner)
                self.btn_SelectAll.setGeometry(QtCore.QRect(50, 310, 121, 31))
                self.btn_SelectAll.setFont(font)
                self.btn_SelectAll.setStyleSheet("color: blue")
                self.btn_SelectAll.setObjectName("btn_SelectAll")
                self.btn_SelectNone = QtWidgets.QPushButton(self.frm_Planner)
                self.btn_SelectNone.setGeometry(QtCore.QRect(240, 310, 121, 31))
                self.btn_SelectNone.setFont(font)
                self.btn_SelectNone.setStyleSheet("color: blue")
                self.btn_SelectNone.setObjectName("btn_SelectNone")
                self.grpBx_DaysOfWeek.raise_()
                self.chkbx_Mon_Br.raise_()
                self.chkbx_Tue_Br.raise_()
                self.chkbx_Wed_Br.raise_()
                self.chkbx_Thu_Br.raise_()
                self.chkbx_Fri_Br.raise_()
                self.chkbx_Sat_Br.raise_()
                self.chkbx_Sun_Br.raise_()
                self.grpBx_Breakfast.raise_()
                self.grpBx_Lunch.raise_()
                self.grpBx_Dinner.raise_()
                self.btn_SelectAll.raise_()
                self.btn_SelectNone.raise_()
                self.tbl_CreateMealPlan = QtWidgets.QTableWidget(self.tab_MealPlan)
                self.tbl_CreateMealPlan.setGeometry(QtCore.QRect(8, 368, 811, 361))
                self.tbl_CreateMealPlan.setFrameShape(QtWidgets.QFrame.WinPanel)
                self.tbl_CreateMealPlan.setFrameShadow(QtWidgets.QFrame.Sunken)
                self.tbl_CreateMealPlan.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
                self.tbl_CreateMealPlan.setTabKeyNavigation(False)
                self.tbl_CreateMealPlan.setProperty("showDropIndicator", False)
                self.tbl_CreateMealPlan.setDragDropOverwriteMode(False)
                self.tbl_CreateMealPlan.setShowGrid(False)
                self.tbl_CreateMealPlan.setSortingEnabled(True)
                self.tbl_CreateMealPlan.setObjectName("tbl_CreateMealPlan")
                self.tbl_CreateMealPlan.horizontalHeader().setCascadingSectionResizes(True)
                self.tbl_CreateMealPlan.verticalHeader().setCascadingSectionResizes(True)
                self.btn_CreateMealPlan = QtWidgets.QPushButton(self.tab_MealPlan)
                self.btn_CreateMealPlan.setGeometry(QtCore.QRect(430, 320, 151, 41))
                self.btn_CreateMealPlan.setObjectName("btn_CreateMealPlan")
                self.tabWidget.addTab(self.tab_MealPlan, "")
                self.tab_View = QtWidgets.QWidget()
                self.tab_View.setObjectName("tab_View")
                self.btn_LoadViewTable = QtWidgets.QPushButton(self.tab_View)
                self.btn_LoadViewTable.setGeometry(QtCore.QRect(10, 20, 151, 51))
                self.btn_LoadViewTable.setFont(font)
                self.btn_LoadViewTable.setObjectName("btn_LoadViewTable")
                self.calViewTab = QtWidgets.QCalendarWidget(self.tab_View)
                self.calViewTab.setEnabled(True)
                self.calViewTab.setGeometry(QtCore.QRect(530, 10, 281, 191))
                self.calViewTab.setFirstDayOfWeek(QtCore.Qt.Monday)
                self.calViewTab.setGridVisible(True)
                self.calViewTab.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.SingleLetterDayNames)
                self.calViewTab.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
                self.calViewTab.setNavigationBarVisible(True)
                self.calViewTab.setDateEditEnabled(False)
                self.calViewTab.setObjectName("calViewTab")
                self.tbl_View = QtWidgets.QTableWidget(self.tab_View)
                self.tbl_View.setGeometry(QtCore.QRect(10, 220, 801, 491))
                self.tbl_View.setObjectName("tbl_View")
                self.tbl_View.setColumnCount(0)
                self.tbl_View.setRowCount(0)
                self.tabWidget.addTab(self.tab_View, "")
                self.tab_Edit = QtWidgets.QWidget()
                self.tab_Edit.setObjectName("tab_Edit")
                self.txtbox_Entree = QtWidgets.QLineEdit(self.tab_Edit)
                self.txtbox_Entree.setGeometry(QtCore.QRect(190, 610, 201, 31))
                self.txtbox_Entree.setFont(font)
                self.txtbox_Entree.setPlaceholderText("")
                self.txtbox_Entree.setObjectName("txtbox_Entree")
                self.btn_add_meal = QtWidgets.QPushButton(self.tab_Edit)
                self.btn_add_meal.setGeometry(QtCore.QRect(680, 690, 131, 31))
                self.btn_add_meal.setFont(font)
                self.btn_add_meal.setStyleSheet("background-color: rgb(255, 170, 0);")
                self.btn_add_meal.setObjectName("btn_add_meal")
                self.txtbox_components = QtWidgets.QLineEdit(self.tab_Edit)
                self.txtbox_components.setGeometry(QtCore.QRect(190, 650, 201, 41))
                self.txtbox_components.setPlaceholderText("")
                self.txtbox_components.setObjectName("txtbox_components")
                self.tbl_Edit = QtWidgets.QTableWidget(self.tab_Edit)
                self.tbl_Edit.setGeometry(QtCore.QRect(10, 60, 801, 461))
                self.tbl_Edit.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.tbl_Edit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
                self.tbl_Edit.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
                self.tbl_Edit.setAlternatingRowColors(True)
                self.tbl_Edit.setShowGrid(False)
                self.tbl_Edit.setCornerButtonEnabled(False)
                self.tbl_Edit.setObjectName("tbl_Edit")
                self.tbl_Edit.setColumnCount(0)
                self.tbl_Edit.setRowCount(0)
                self.tbl_Edit.verticalHeader().setVisible(True)
                self.cmbBx_MealType = QtWidgets.QComboBox(self.tab_Edit)
                self.cmbBx_MealType.setGeometry(QtCore.QRect(190, 570, 201, 31))
                self.cmbBx_MealType.setFont(font)
                self.cmbBx_MealType.setObjectName("cmbBx_MealType")
                self.cmbBx_MealType.addItem("Select Meal Type")
                self.cmbBx_MealType.addItem("Breakfast")
                self.cmbBx_MealType.addItem("Lunch")
                self.cmbBx_MealType.addItem("Dinner")
                self.lbl_EditHeading = QtWidgets.QLabel(self.tab_Edit)
                self.lbl_EditHeading.setGeometry(QtCore.QRect(10, 530, 311, 21))
                self.lbl_EditHeading.setFont(font)
                self.lbl_EditHeading.setObjectName("lbl_EditHeading")
                self.lbl_MealType = QtWidgets.QLabel(self.tab_Edit)
                self.lbl_MealType.setGeometry(QtCore.QRect(70, 570, 111, 31))
                self.lbl_MealType.setFont(font)
                self.lbl_MealType.setObjectName("lbl_MealType")
                self.lbl_Entree = QtWidgets.QLabel(self.tab_Edit)
                self.lbl_Entree.setGeometry(QtCore.QRect(70, 610, 111, 31))
                self.lbl_Entree.setFont(font)
                self.lbl_Entree.setObjectName("lbl_Entree")
                self.lbl_Components = QtWidgets.QLabel(self.tab_Edit)
                self.lbl_Components.setGeometry(QtCore.QRect(70, 650, 111, 41))
                self.lbl_Components.setFont(font)
                self.lbl_Components.setObjectName("lbl_Components")
                self.lbl_SideItems = QtWidgets.QLabel(self.tab_Edit)
                self.lbl_SideItems.setGeometry(QtCore.QRect(430, 570, 111, 31))
                self.lbl_SideItems.setFont(font)
                self.lbl_SideItems.setObjectName("lbl_SideItems")
                self.txtbox_SideItems = QtWidgets.QLineEdit(self.tab_Edit)
                self.txtbox_SideItems.setGeometry(QtCore.QRect(550, 570, 201, 31))
                self.txtbox_SideItems.setPlaceholderText("")
                self.txtbox_SideItems.setObjectName("txtbox_SideItems")
                self.txtbox_Condiments = QtWidgets.QLineEdit(self.tab_Edit)
                self.txtbox_Condiments.setGeometry(QtCore.QRect(550, 610, 201, 31))
                self.txtbox_Condiments.setPlaceholderText("")
                self.txtbox_Condiments.setObjectName("txtbox_Condiments")
                self.lbl_GroceryList = QtWidgets.QLabel(self.tab_Edit)
                self.lbl_GroceryList.setGeometry(QtCore.QRect(430, 650, 111, 31))
                self.lbl_GroceryList.setFont(font)
                self.lbl_GroceryList.setObjectName("lbl_GroceryList")
                self.txtbox_GroceryList = QtWidgets.QLineEdit(self.tab_Edit)
                self.txtbox_GroceryList.setGeometry(QtCore.QRect(550, 650, 201, 31))
                self.txtbox_GroceryList.setPlaceholderText("")
                self.txtbox_GroceryList.setObjectName("txtbox_GroceryList")
                self.lbl_Condiments = QtWidgets.QLabel(self.tab_Edit)
                self.lbl_Condiments.setGeometry(QtCore.QRect(430, 610, 111, 31))
                self.lbl_Condiments.setFont(font)
                self.lbl_Condiments.setObjectName("lbl_Condiments")
                self.lbl_Heading_2 = QtWidgets.QLabel(self.tab_Edit)
                self.lbl_Heading_2.setGeometry(QtCore.QRect(10, 20, 311, 21))
                self.lbl_Heading_2.setFont(font)
                self.lbl_Heading_2.setObjectName("lbl_Heading_2")
                self.btn_DeleteEdit = QtWidgets.QPushButton(self.tab_Edit)
                self.btn_DeleteEdit.setGeometry(QtCore.QRect(640, 10, 171, 41))
                self.btn_DeleteEdit.setFont(font)
                self.btn_DeleteEdit.setAutoFillBackground(False)
                self.btn_DeleteEdit.setStyleSheet("background-color: rgb(205, 0, 0);\n"
                                                    "color: white;")
                self.btn_DeleteEdit.setObjectName("btn_DeleteEdit")
                self.btn_LoadEditTable = QtWidgets.QPushButton(self.tab_Edit)
                self.btn_LoadEditTable.setGeometry(QtCore.QRect(120, 10, 131, 41))
                self.btn_LoadEditTable.setObjectName("btn_LoadEditTable")
                self.tabWidget.addTab(self.tab_Edit, "")
                win_MealPlanner.setCentralWidget(self.centralwidget)
                self.statusbar = QtWidgets.QStatusBar(win_MealPlanner)
                self.statusbar.setObjectName("statusbar")
                win_MealPlanner.setStatusBar(self.statusbar)
                self.actionNew = QtWidgets.QAction(win_MealPlanner)
                self.actionNew.setObjectName("actionNew")
                self.actionSave = QtWidgets.QAction(win_MealPlanner)
                self.actionSave.setObjectName("actionSave")
                self.actionCopy = QtWidgets.QAction(win_MealPlanner)
                self.actionCopy.setObjectName("actionCopy")
                self.actionPaste = QtWidgets.QAction(win_MealPlanner)
                self.actionPaste.setObjectName("actionPaste")
                self.retranslateUi(win_MealPlanner)
                self.tabWidget.setCurrentIndex(0)
                QtCore.QMetaObject.connectSlotsByName(win_MealPlanner)

                self.btn_LoadEditTable.clicked.connect(self.loadEditTable)
                self.btn_LoadViewTable.clicked.connect(self.loadVeiwTable)
                self.btn_SelectAll.clicked.connect(self.add_checkbox)
                self.btn_SelectNone.clicked.connect(self.count_checkbox)
                self.btn_CreateMealPlan.clicked.connect(self.createMealPlan)
                
        def retranslateUi(self, win_MealPlanner):
                _translate = QtCore.QCoreApplication.translate
                win_MealPlanner.setWindowTitle(_translate("win_MealPlanner", "Meal Planner"))
                self.grpBx_Breakfast.setTitle(_translate("win_MealPlanner", "Breakfast"))
                self.grpBx_Lunch.setTitle(_translate("win_MealPlanner", "Lunch"))
                self.grpBx_Dinner.setTitle(_translate("win_MealPlanner", "Dinner"))
                self.lbl_Tue.setText(_translate("win_MealPlanner", "Tuesday"))
                self.lbl_Wed.setText(_translate("win_MealPlanner", "Wednesday"))
                self.lbl_Mon.setText(_translate("win_MealPlanner", "Monday"))
                self.lbl_Thu.setText(_translate("win_MealPlanner", "Thursday"))
                self.lbl_Fri.setText(_translate("win_MealPlanner", "Friday"))
                self.lbl_Sat.setText(_translate("win_MealPlanner", "Saturday"))
                self.lbl_Sun.setText(_translate("win_MealPlanner", "Sunday"))
                self.btn_SelectAll.setText(_translate("win_MealPlanner", "Select All"))
                self.btn_SelectNone.setText(_translate("win_MealPlanner", "Select None"))
                self.btn_CreateMealPlan.setText(_translate("win_MealPlanner", "Create Meal Plan"))
                self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_MealPlan), _translate("win_MealPlanner", "Create Meal Plan"))
                self.btn_LoadViewTable.setText(_translate("win_MealPlanner", "Get Meal List"))
                self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_View), _translate("win_MealPlanner", "View Meal List"))
                self.btn_add_meal.setText(_translate("win_MealPlanner", "Add Meal"))
                self.tbl_Edit.setSortingEnabled(False)
                self.lbl_EditHeading.setText(_translate("win_MealPlanner", "Enter new meals into database:"))
                self.lbl_MealType.setText(_translate("win_MealPlanner", "Meal Type:"))
                self.lbl_Entree.setText(_translate("win_MealPlanner", "Entree:"))
                self.lbl_Components.setText(_translate("win_MealPlanner", "Components:"))
                self.lbl_SideItems.setText(_translate("win_MealPlanner", "Side Items:"))
                self.lbl_GroceryList.setText(_translate("win_MealPlanner", "Grocery List:"))
                self.lbl_Condiments.setText(_translate("win_MealPlanner", "Condiments:"))
                self.lbl_Heading_2.setText(_translate("win_MealPlanner", "Meal List:"))
                self.btn_DeleteEdit.setText(_translate("win_MealPlanner", "Delete Selected Meal"))
                self.btn_LoadEditTable.setText(_translate("win_MealPlanner", "Get Meal List"))
                self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Edit), _translate("win_MealPlanner", "Edit Meal List"))
                self.actionNew.setText(_translate("win_MealPlanner", "New"))
                self.actionNew.setStatusTip(_translate("win_MealPlanner", "Create a new file"))
                self.actionNew.setShortcut(_translate("win_MealPlanner", "Ctrl+N"))
                self.actionSave.setText(_translate("win_MealPlanner", "Save"))
                self.actionSave.setStatusTip(_translate("win_MealPlanner", "Save the current file"))
                self.actionSave.setShortcut(_translate("win_MealPlanner", "Ctrl+S"))
                self.actionCopy.setText(_translate("win_MealPlanner", "Copy"))
                self.actionCopy.setStatusTip(_translate("win_MealPlanner", "Copy selected text"))
                self.actionCopy.setShortcut(_translate("win_MealPlanner", "Ctrl+C"))
                self.actionPaste.setText(_translate("win_MealPlanner", "Paste"))
                self.actionPaste.setStatusTip(_translate("win_MealPlanner", "Paste copied text"))
                self.actionPaste.setShortcut(_translate("win_MealPlanner", "Ctrl+V"))


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        win_MealPlanner = QtWidgets.QMainWindow()
        ui = Ui_win_MealPlanner()
        ui.setupUi(win_MealPlanner)

        # win_MealPlanner.setFont(font)
        win_MealPlanner.show()
        sys.exit(app.exec_())

